# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mbti_chractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti', models.CharField(max_length=20)),
                ('charactor', models.CharField(max_length=60)),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mbti_major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_new', models.CharField(max_length=30)),
                ('classes', models.CharField(max_length=30)),
                ('mbti', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='nation_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('province', models.CharField(max_length=10)),
                ('classy', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=50)),
                ('line', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pro_univer_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=10)),
                ('classy', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('lowest', models.IntegerField()),
                ('hightst', models.IntegerField()),
                ('average', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('batch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='univer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('leixing', models.CharField(max_length=30)),
                ('lishuyu', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=10)),
                ('academician', models.IntegerField(default=0)),
                ('doctor', models.IntegerField(default=0)),
                ('master', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=40)),
                ('website', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=20)),
                ('city', models.CharField(default='', max_length=60)),
                ('provincial_capital', models.CharField(default='', max_length=60)),
                ('development', models.CharField(default='', max_length=60)),
                ('leixing_int', models.IntegerField(default=0)),
                ('is_doctor', models.IntegerField(default=0)),
                ('is_master', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='univer_major_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=30)),
                ('average', models.CharField(max_length=10)),
                ('hightst', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=10)),
                ('classy', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('batch', models.CharField(max_length=50)),
                ('major_new', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('point', models.IntegerField()),
                ('yingjie', models.CharField(max_length=30)),
                ('hukou', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=30)),
                ('kelei', models.CharField(max_length=30)),
                ('nation', models.CharField(max_length=30)),
                ('add_point', models.IntegerField()),
                ('mbti', models.CharField(max_length=30)),
                ('major_recom_interst', models.CharField(max_length=300)),
                ('recommend', models.CharField(max_length=300)),
            ],
        ),
    ]
