# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='univer_major_pro_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=30)),
                ('average', models.CharField(max_length=10)),
                ('hightst', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=10)),
                ('classy', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('batch', models.CharField(max_length=50)),
                ('major_new', models.CharField(default='', max_length=30)),
                ('lowest_pro', models.IntegerField()),
                ('hightst_pro', models.IntegerField()),
                ('average_pro', models.IntegerField()),
                ('amount_pro', models.IntegerField()),
                ('batch_pro', models.CharField(max_length=50)),
            ],
        ),
    ]
