# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_univer_major_pro_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation_line',
            name='line',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nation_line',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pro_univer_point',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pro_univer_point',
            name='average',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pro_univer_point',
            name='hightst',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pro_univer_point',
            name='lowest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pro_univer_point',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='univer_info',
            name='is_doctor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='univer_info',
            name='is_master',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='univer_info',
            name='leixing_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='univer_major_line',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='univer_major_pro_line',
            name='amount_pro',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='univer_major_pro_line',
            name='average_pro',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='univer_major_pro_line',
            name='hightst_pro',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='univer_major_pro_line',
            name='lowest_pro',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='univer_major_pro_line',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='add_point',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='point',
            field=models.IntegerField(null=True),
        ),
    ]
