# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_pro_univer_nation_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_univer_nation_line',
            name='d_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pro_univer_nation_line',
            name='d_h',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pro_univer_nation_line',
            name='d_ha',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pro_univer_nation_line',
            name='d_hl',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pro_univer_nation_line',
            name='d_l',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pro_univer_nation_line',
            name='d_la',
            field=models.IntegerField(null=True),
        ),
    ]
