# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_auto_20171206_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='nation_line_lowest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('province', models.CharField(max_length=10)),
                ('classy', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=50)),
                ('line', models.IntegerField(null=True)),
            ],
        ),
    ]
