# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_nation_line_lowest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation_line_lowest',
            name='batch',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
