# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0010_univer_major_line_lb'),
    ]

    operations = [
        migrations.AddField(
            model_name='univer_info',
            name='school_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='univer_info',
            name='school_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='univer_major_line_lb',
            name='major_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='univer_major_line_lb',
            name='school_rank',
            field=models.IntegerField(null=True),
        ),
    ]
