# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0011_auto_20171220_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='univer_major_line_lb',
            name='recruit_count',
            field=models.IntegerField(null=True),
        ),
    ]
