# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0012_univer_major_line_lb_recruit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='univer_info_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('leixing', models.CharField(max_length=30)),
                ('lishuyu', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=10)),
                ('academician', models.IntegerField(default=0)),
                ('doctor', models.IntegerField(default=0)),
                ('master', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=40)),
                ('website', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=20)),
                ('city', models.CharField(default='', max_length=60)),
                ('development', models.CharField(default='', max_length=60)),
                ('school_rank', models.IntegerField(null=True)),
                ('school_type', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
