# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0014_province_school_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_type',
            old_name='province',
            new_name='school_type',
        ),
    ]
